// Conecctiones entre los nidos, formato de a pares:
exports.connections = [
    "Church Tower-Sportsgrounds",
    "Church Tower-Big Maple",
    "Big Maple-Sportsgrounds",
    "Big Maple-Woods",
    "Big Maple-Fabienne's Garden",
    "Fabienne's Garden-Woods",
    "Fabienne's Garden-Cow Pasture",
    "Cow Pasture-Big Oak",
    "Big Oak-Butcher Shop",
    "Butcher Shop-Tall Poplar",
    "Tall Poplar-Sportsgrounds",
    "Tall Poplar-Chateau",
    "Chateau-Great Pine",
    "Great Pine-Jacques' Farm",
    "Jacques' Farm-Hawthorn",
    "Great Pine-Hawthorn",
    "Hawthorn-Gilles' Garden",
    "Great Pine-Gilles' Garden",
    "Gilles' Garden-Big Oak",
    "Gilles' Garden-Butcher Shop",
    "Chateau-Butcher Shop",
  ];